name: Workflows Test custom action

on: 
  push:
  pull_request:

jobs:
  test-custom-action:
    name: Test custom action
    runs-on: ubuntu-latest
    steps:
      - uses: ribafish/github-ac5tions/gradle-run@main
        with:
          gradle_task: "tasks"
          workDir: 'testPath'
      
