name: Verify Build

on:
    push:
        branches: [ main ]
    pull_request:
    workflow_dispatch:
        inputs:
            enabled:
                description: Boolean input
                required: true
                default: false
                type: boolean

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - id: test
              run: |
                  echo "${{ github.ref_name }}"
                  echo "${{ github.event }}"
                  echo "${{ github }}"
                  echo "${{ github.base_ref }}"
                  echo "${{ github.event_name }}"
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                  echo "$ENABLED"
                  echo "$ENABLED3"
            - name: Inputs
              env:
                  ENABLED: $(if ${{ github.event.inputs.enabled == '' }}; then echo 'true'; else echo '${{ github.event.inputs.enabled }}'; fi)
                  ENABLED3: ${{ github.event.inputs.enabled }}
              run: |
                  echo "$ENABLED"
                  echo "$(if ${{ github.event.inputs.enabled == '' }}; then echo 'true'; else echo '${{ github.event.inputs.enabled }}'; fi)" >> ENABLED2
            - name: Print ENABLED2
              run: echo "$ENABLED2"


