name: Trigger the build-verification workflow

on:
    workflow_dispatch:

jobs:
    trigger:
        name: Staging Release
        runs-on: ubuntu-latest
        steps:
            - name: Trigger tests
              uses: convictional/trigger-workflow-and-wait@v1.6.5
              with:
                  owner: ribafish
                  repo: gh-actions-test
                  ref: main
                  workflow_file_name: build-verification.yml
                  github_token: ${{ secrets.GH_BOT_GITHUB_TOKEN }}
