name: Verify Build

on:
    push:
        branches: [ main ]
    pull_request:
    workflow_dispatch:
        inputs:
            enabled:
                description: Boolean input
                required: true
                default: false
                type: boolean

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - id: test
              run: |
                  echo "${{ github.ref_name }}"
                  echo "${{ github.event }}"
                  echo "${{ github }}"
                  echo "${{ github.base_ref }}"
                  echo "${{ github.event_name }}"
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
                  ENABLED: ${{ github.event.inputs.enabled }}
              run: |
                  echo "$GITHUB_CONTEXT"
                  echo "$ENABLED"

