name: Verify Build

on:
    push:
        branches: [ main ]
    pull_request:
    workflow_dispatch:
        inputs:
            enabled:
                description: Boolean input
                required: true
                default: false
                type: boolean

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - id: test
              run: |
                  echo "${{ github.ref_name }}"
                  echo "${{ github.event }}"
                  echo "${{ github }}"
                  echo "${{ github.base_ref }}"
                  echo "${{ github.event_name }}"
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: |
                  echo "$ENABLED"
                  echo "$ENABLED3"
            - name: Inputs
              env:
                  ENABLED: $(if ${{ github.event.inputs.enabled == '' }}; then echo 'true'; else echo '${{ github.event.inputs.enabled }}'; fi)
                  ENABLED3: ${{ github.event.inputs.enabled }}
              run: |
                  echo "$ENABLED"
                  echo "$(if ${{ github.event.inputs.enabled == '' }}; then echo 'true'; else echo '${{ github.event.inputs.enabled }}'; fi)" >> ENABLED2
            - name: Print ENABLED2
              run: echo "$ENABLED2"
            - name: Check pts mode in ENV
              env:
                PTS_MODE: "${{ github.ref_name == 'main' && 'REMAINING_TESTS' || 'RELEVANT_TESTS' }}"
              run: echo "$PTS_MODE"
            - name: Get job id and stuff
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              run: |
                  jobs=$(gh api repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/attempts/$GITHUB_RUN_ATTEMPT/jobs)
                  job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="$RUNNER_NAME") | .id')
                  echo "jobs=$jobs"
                  echo "job_execution_id=$job_id"
                  echo "job_id=$GITHUB_JOB"
                  echo "workflow_name=$GITHUB_WORKFLOW"
    test_noname:
        runs-on: ubuntu-latest
        steps:
            - name: Get job id and stuff
              env:
                GITHUB_TOKEN: ${{ github.token }}
              run: |
                  jobs=$(gh api repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/attempts/$GITHUB_RUN_ATTEMPT/jobs)
                  job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="$RUNNER_NAME") | .id')
                  echo "jobs=$jobs"
                  echo "job_execution_id=$job_id"
                  echo "job_id=$GITHUB_JOB"
                  echo "workflow_name=$GITHUB_WORKFLOW"


