name: Matrix with use

on:
  push:
    branches:
      - main

jobs:

  timeout-runner:
    uses: ribafish/gh-actions-test/.github/workflows/reusable_workflow.yml@8891b7e5d6333d0e214522870340c7892d203dfb
    with:
      arg: thing
      timeout-minutes: 10

  # matrix-runner:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       args: [1,2,3,4]
  #   steps:
  #     - name: "Matrixed step"
  #       uses: ribafish/gh-actions-test/.github/workflows/reusable_workflow.yml@f25d49dca916279bbe809b677983e703e0877d12
  #       with:
  #         arg: ${{ matrix.args }}
