name: Matrix with use

on:
  workflow_dispatch

jobs:

  timeout-runner:
    uses: ribafish/gh-actions-test/.github/workflows/reusable_workflow.yml@5b1df629a952267330aa41e2a8927a0e598b8dbe
    with:
      arg: thing
      timeout-minutes: 10

  # matrix-runner:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       args: [1,2,3,4]
  #   steps:
  #     - name: "Matrixed step"
  #       uses: ribafish/gh-actions-test/.github/workflows/reusable_workflow.yml@f25d49dca916279bbe809b677983e703e0877d12
  #       with:
  #         arg: ${{ matrix.args }}
