name: Test semver and release

on:
  push:
    branches:
      - 'main'
      
jobs:
  upload1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo upload1 >> upload1.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: upload1.txt
          path: upload1.txt
      
  upload2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo upload2 >> upload2.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: upload2.txt
          path: upload2.txt
   
  release:
    needs:
      - upload1
      - upload2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Semver
        uses: paulhatch/semantic-version@v3.3
        id: version
        with:
          # The prefix to use to identify tags
          branch: "main"
          
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          release_name: Release ${{ steps.version.outputs.version_tag }}
          draft: false
          
      - name: Upload Release Asset1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: artifacts/upload1.txt
          asset_name: upload1.txt
          asset_content_type: application/zip
      - name: Upload Release Asset2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: artifacts/upload2.txt
          asset_name: upload2.txt
          asset_content_type: application/zip
