name: Workflows on push with path
on: 
  push:
    branches:
      - main
jobs:
  gradle-testPath:
    name: Test path conditionals
    uses: ribafish/gh-actions-test/.github/workflows/job_gradle_run.yml@main
    with:
      gradle_task: |
        tasks
        help
        projects
        properties
      workDir: 'testPath'
      
