name: Test semver and release

on:
  push:
    branches:
      - 'main'
      
jobs:
  upload12:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [upload1,upload2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo ${{ matrix.name }} >> ${{ matrix.name }}.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}.xt
          path: ${{ matrix.name }}.txt
      
  upload34:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [upload3,upload4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo ${{ matrix.name }} >> ${{ matrix.name }}.txt
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}.txt
   
  release:
    needs:
      - upload12
      - upload34
    runs-on: ubuntu-latest
    outputs:
      release_upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Semver
        uses: paulhatch/semantic-version@v3.3
        id: version
        with:
          # The prefix to use to identify tags
          branch: "main"
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version_tag }}
          release_name: Release ${{ steps.version.outputs.version_tag }}
          draft: false
          
  release-artifacts:
    needs: 
      - release
#       - upload12
#       - upload34
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        file: [upload1,upload2,upload3,upload4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.file }}
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Upload Release Asset1
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          upload_url: ${{ needs.release.outputs.release_upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: artifacts/${{ matrix.file }}.txt
          asset_name: ${{ matrix.file }}
          asset_content_type: application/zip
