name: Workflows on push with path
on: 
  push:
    branches:
      - main
    paths:
      - 'testPath/**'
jobs:
  gradle-testPath:
    name: Test path conditionals
    uses: ./.github/action_gradle_run
    with:
      gradle_task: "tasks --all"
      workDir: 'testPath'
      
