name: Workflows on push with path
on: 
  push:
    branches:
      - main
    paths:
      - 'testPath/**'
jobs:
  gradle-testPath:
    name: Test path conditionals
    uses: ribafish/gh-actions-test/.github/workflows/job_gradle_run.yml@3fa9a0b309f4327b5a74e4d46ccf9f9406d60baa
    with:
      gradle_task: "tasks"
      workDir: 'testPath'
      
