name: Workflows on push with path
on: 
  push:
    branches:
      - main
    paths:
      - 'testPath/**'
jobs:
  gradle-testPath:
    name: Test path conditionals
    uses: ribafish/gh-actions-test/.github/workflows/action_gradle_run.yml@ff110067f138f0697b592f51fc1365a857f34767
    with:
      gradle_task: "tasks --all"
      workDir: 'testPath'
      
