name: App Distribution - Current

on:
  push:
    branches:
      - 'main'
      - 'feature/somefeature'
      
jobs:
  dostuff:
    if: github.actor != 'GHA-Bot'
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        
      - name: Update file
        run: echo "stuff" >> file.txt

      - name: Update file2
        run: echo $GITHUB_SHA_SHORT >> file.txt
        
      - name: Update git props
        run: |
          git config --global user.name 'GHA-Bot'
          git config --global user.email '<>'

      - name: Git commit
        run: |
          git add -A
          git commit -m "Test push changes [Skip CI]"

      - name: git push
        run: |
          git push
          git push --tags

      - name: touch file
        run: touch fileTouch-$GITHUB_SHA_SHORT.txt

      - name: Upload apk
        uses: actions/upload-artifact@v3
        with:
          name: fileTouch-${{ env.GITHUB_SHA_SHORT }}.txt
          path: fileTouch-${{ env.GITHUB_SHA_SHORT }}.txt

      
      # - name: Check env
      #   env:
      #     TEST_ENV_VAR: "Something Special"
      #   run: |
      #     printenv
      
      # - name: Tag
      #   run: |
      #     git tag -a "v1.2" -m "v1.2"
      
      # - name: Push commit and tags
      #   run: |
      #     git push origin main --tags
    
  
