name: App Distribution - Current

on:
  push:
    branches:
      - 'main'
      
jobs:
  dostuff:
    if: github.actor != 'GHA-Bot'
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout branch
        uses: actions/checkout@v2
        
      - name: Update file
        run: echo "stuff" >> file.txt
        
      - name: Update Gradle props
        run: |
          git config --global user.name 'GHA-Bot'
          git config --global user.email '<>'
      
      - name: Tag
        run: |
          git tag -a "v1.2" -m "v1.2"
      
      - name: Push commit and tags
        run: |
          git push origin main --tags
      
  
