name: Manual CurrentProdDebug build workflow

on:
  workflow_dispatch:

jobs:

  assemble_prod_debug_apk:
    uses: ribafish/gh-actions-test/.github/workflows/reusable_workflow.yml@8891b7e5d6333d0e214522870340c7892d203dfb
    with:
      arg: ":target:mobile:app:assembleCurrentProdDebug"
      timeout-minutes: 10
