name: Workflows on push with path
on: 
  push:
    branches:
      - main
    paths:
      - 'testPath/**'
jobs:
  gradle-testPath:
    name: Test path conditionals
    uses: ribafish/gh-actions-test/.github/actions/action_gradle_run.yml@5258022b5a71741585dcd0673c2809933bf24f12
    with:
      gradle_task: "tasks --all"
      workDir: 'testPath'
      
