name: Parse branch and commit

on: 
  workflow_dispatch:
  push:
    branches: 
      - feature/somefeature

jobs:
  parse:
    runs-on: ubuntu-latest
    outputs: 
      branch_sha: ${{ steps.output.outputs.branch_sha }}
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - id: output
        run: echo "::set-output name=branch_sha::${GITHUB_REF_SLUG}_${GITHUB_SHA_SHORT}"
  use:
    needs: parse
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ needs.parse.outputs.branch_sha }}"
    
