name: App Distribution - Current

on:
  push:
    branches:
      - 'test_push'
      
jobs:
  dostuff:
    if: github.actor != 'GHA-Bot'
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout branch
        uses: actions/checkout@v2
        
      - name: Update file
        run: echo "stuff" >> file.txt
        
      - name: Update Gradle props
        run: |
          git config --global user.name 'GHA-Bot'
          git config --global user.email '<>'
          git add file.txt
          git commit -m "Updated file"
      
      - name: Push commit and tags
        run: |
          git push origin test_push --tags
      
  
