name: Manual CurrentProdDebug build workflow

on:
  workflow_dispatch:
    inputs:
      force_version_code:
        description: 'Force the built version code to the specified number [leave empty unless needed!]'
        required: false
        default: ''

jobs:

  assemble_prod_debug_apk:
    name: Manual build CurrentProdDebug apk
    if: github.event.inputs.force_version_code == ''
    uses: ribafish/gh-actions-test/.github/workflows/reusable_workflow.yml@8891b7e5d6333d0e214522870340c7892d203dfb
    with:
      arg: :target:mobile:app:assembleCurrentProdDebug
      timeout-minutes: 10
      
  assemble_prod_debug_apk_force_version_code:
    name: Manual build prod debug apk - Forced version code
    if: github.event.inputs.force_version_code != ''
    uses: ribafish/gh-actions-test/.github/workflows/reusable_workflow.yml@8891b7e5d6333d0e214522870340c7892d203dfb
    with:
      arg: "forceVersionCode --code ${{ github.event.inputs.force_version_code }} clean :target:mobile:app:assembleCurrentProdDebug"
      timeout-minutes: 10
